
# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - documentation/*
    - THIRD-PARTY-NOTICES.TXT
    - LICENSE.TXT

stages:
  - stage: build
    displayName: Build and Test Diagnostics
    jobs:
