trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - documentation/*
    - THIRD-PARTY-NOTICES.TXT
    - LICENSE.TXT

stages:
  - stage: build
    displayName: Build and Test Diagnostics
    jobs:

    ############################
    #                          #
    #    Source Build legs     #
    #                          #
    ############################

    - template: /eng/common/templates/job/source-build.yml
      parameters:
        platform:
          name: Complete
          buildScript: ./eng/common/build.sh